-- begin CURRADDON_CURRENCY
create unique index IDX_CURRADDON_CURRENCY_UNIQ_CODE on CURRADDON_CURRENCY (CODE) ^
-- end CURRADDON_CURRENCY
-- begin CURRADDON_CURRENCY_RATE
alter table CURRADDON_CURRENCY_RATE add constraint FK_CURRADDON_CURRENCY_RATE_ON_CURRENCY foreign key (CURRENCY_ID) references CURRADDON_CURRENCY(ID)^
alter table CURRADDON_CURRENCY_RATE add constraint FK_CURRADDON_CURRENCY_RATE_ON_TARGET_CURRENCY foreign key (TARGET_CURRENCY_ID) references CURRADDON_CURRENCY(ID)^
create index IDX_CURRADDON_CURRENCY_RATE_ON_CURRENCY on CURRADDON_CURRENCY_RATE (CURRENCY_ID)^
create index IDX_CURRADDON_CURRENCY_RATE_ON_TARGET_CURRENCY on CURRADDON_CURRENCY_RATE (TARGET_CURRENCY_ID)^
-- end CURRADDON_CURRENCY_RATE
-- begin CURRADDON_CURRENCY_VALUE
alter table CURRADDON_CURRENCY_VALUE add constraint FK_CURRADDON_CURRENCY_VALUE_ON_CURRENCY foreign key (CURRENCY_ID) references CURRADDON_CURRENCY(ID)^
create index IDX_CURRADDON_CURRENCY_VALUE_ON_CURRENCY on CURRADDON_CURRENCY_VALUE (CURRENCY_ID)^
-- end CURRADDON_CURRENCY_VALUE
