-- begin CURRADDON_CURRENCY_DESCRIPTOR
create unique index IDX_CURRADDON_CURRENCY_DESCRIPTOR_UK_CODE on CURRADDON_CURRENCY_DESCRIPTOR (CODE) where DELETE_TS is null ^
-- end CURRADDON_CURRENCY_DESCRIPTOR
-- begin CURRADDON_CURRENCY_RATE
alter table CURRADDON_CURRENCY_RATE add constraint FK_CURRADDON_CURRENCY_RATE_ON_CURRENCY foreign key (CURRENCY_ID) references CURRADDON_CURRENCY_DESCRIPTOR(ID)^
alter table CURRADDON_CURRENCY_RATE add constraint FK_CURRADDON_CURRENCY_RATE_ON_TARGET_CURRENCY foreign key (TARGET_CURRENCY_ID) references CURRADDON_CURRENCY_DESCRIPTOR(ID)^
create index IDX_CURRADDON_CURRENCY_RATE_ON_CURRENCY on CURRADDON_CURRENCY_RATE (CURRENCY_ID)^
create index IDX_CURRADDON_CURRENCY_RATE_ON_TARGET_CURRENCY on CURRADDON_CURRENCY_RATE (TARGET_CURRENCY_ID)^
-- end CURRADDON_CURRENCY_RATE
-- begin CURRADDON_CURRENCY
alter table CURRADDON_CURRENCY add constraint FK_CURRADDON_CURRENCY_ON_CURRENCY foreign key (CURRENCY_ID) references CURRADDON_CURRENCY_DESCRIPTOR(ID)^
create index IDX_CURRADDON_CURRENCY_ON_CURRENCY on CURRADDON_CURRENCY (CURRENCY_ID)^
-- end CURRADDON_CURRENCY
